name: Build and push the edge image

on:
    push:
        branches:
            - master

jobs:
    run-pre-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: |
                  sudo mkdir /captain
                  npm ci
                  npm run build
                  npm run lint
                  npm run formatter
                  sudo npm run test
    build-publish-docker-hub:
        needs: run-pre-checks
        runs-on: ubuntu-latest
        steps:
            - uses: azure/docker-login@v1
              with:
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - uses: actions/checkout@v1
            - name: Build and Push Edge to DockerHub
              shell: bash
              run: ./dev-scripts/build_and_push_edge.sh
